ada_decay_rate: 0.99999
ada_epsilon: 1e-8
avg_decay_rate: 0.999993
back_propagate_input: true
embedding:
  create_threshold: 0
  initial_g2sum: 3
  initial_range: 2
  learning_rate: 0.01
  slots_config:
  - compress_group: USER
    dim: 32
    dtype: float32
    input_name: uid_emb
    slots: 38 34
  - compress_group: USER
    dim: 8
    dtype: float32
    input_name: uid_stat
    slots: 184 35 189
  - compress_group: USER
    dim: 8
    dtype: float32
    input_name: did_stat
    slots: 701 702 703 704 705 706
  - compress_group: USER
    dim: 8
    dtype: float32
    input_name: u_mean_stat
    slots: 950 952 954 956 958 960
  - compress_group: USER
    dim: 8
    dtype: float32
    input_name: u_std_stat
    slots: 951 953 955 957 959 961
  - dim: 8
    dtype: float32
    input_name: photo_category_idx0
    slots: 201 202
  - dim: 8
    dtype: float32
    input_name: photo_category_idx1
    slots: 10201 10202
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_1
    slots: '901'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_2
    slots: '902'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_3
    slots: '903'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_4
    slots: '904'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_5
    slots: '905'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_6
    slots: '906'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_7
    slots: '907'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_8
    slots: '908'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_9
    slots: '909'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_10
    slots: '910'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_11
    slots: '911'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_12
    slots: '912'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_13
    slots: '913'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_14
    slots: '914'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_15
    slots: '915'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_16
    slots: '916'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_17
    slots: '917'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_18
    slots: '918'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_19
    slots: '919'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_20
    slots: '920'
  - compress_group: USER
    dim: 8
    dtype: float32
    expand: 20
    input_name: uid_action_list_21
    slots: '921'
  version_aware: true
  weight_bounds:
  - -10
  - 10
extra_params: []
extra_preds: like_weight follow_weight forward_weight comment_weight longview_weight
  effective_view_weight like_weight_idx1 follow_weight_idx1 forward_weight_idx1 comment_weight_idx1
  longview_weight_idx1 effective_view_weight_idx1
global_init_range: 0.2
graph: ../config/graph.pb
graph_targets:
- opt
graph_tensor_mapping:
  comment_weight: split:3
  comment_weight_idx1: split_1:3
  effective_view_weight: split:5
  effective_view_weight_idx1: split_1:5
  follow_weight: split:1
  follow_weight_idx1: split_1:1
  forward_weight: split:2
  forward_weight_idx1: split_1:2
  like_weight: split:0
  like_weight_idx1: split_1:0
  longview_weight: split:4
  longview_weight_idx1: split_1:4
hyperparameter_kconf: null
input_type: 3
learning_rate: 5.0e-06
mom_decay_rate: 0.999
output_hidden_units: update_input continue_normlized_input slide_embedding slide_wide
  watch_time_wide position_weight_input
param:
- coln: 32
  dtype: float32
  init_mean: 0
  init_range: 1
  name: seq_encoder/dense/kernel
  rown: 168
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: seq_encoder/dense/bias
  rank: 1
  rown: 32
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_predictor/dense/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: intent_predictor/dense/bias
  rank: 1
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_emb/dense/kernel
  rown: 16
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: intent_emb/dense/bias
  rank: 1
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: pxtr_idx0_self_attention/dense/kernel
  rown: 6
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: pxtr_idx0_self_attention/dense_1/kernel
  rown: 6
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: pxtr_idx0_self_attention/dense_2/kernel
  rown: 6
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: pxtr_idx0_self_attention/dense_3/kernel
  rown: 16
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: pxtr_idx0_self_attention/dense_3/bias
  rank: 1
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: pxtr_idx1_self_attention/dense/kernel
  rown: 6
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: pxtr_idx1_self_attention/dense_1/kernel
  rown: 6
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: pxtr_idx1_self_attention/dense_2/kernel
  rown: 6
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: pxtr_idx1_self_attention/dense_3/kernel
  rown: 16
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: pxtr_idx1_self_attention/dense_3/bias
  rank: 1
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_pxtr_idx0_attention/dense/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_pxtr_idx0_attention/dense_1/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_pxtr_idx0_attention/dense_2/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_pxtr_idx0_attention/dense_3/kernel
  rown: 16
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: intent_aware_cross_pxtr_idx0_attention/dense_3/bias
  rank: 1
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_pxtr_idx1_attention/dense/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_pxtr_idx1_attention/dense_1/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_pxtr_idx1_attention/dense_2/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_pxtr_idx1_attention/dense_3/kernel
  rown: 16
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: intent_aware_cross_pxtr_idx1_attention/dense_3/bias
  rank: 1
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_category_attention_idx0/dense/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_category_attention_idx0/dense_1/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_category_attention_idx0/dense_2/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_category_attention_idx0/dense_3/kernel
  rown: 16
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: intent_aware_cross_category_attention_idx0/dense_3/bias
  rank: 1
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_category_attention_idx1/dense/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_category_attention_idx1/dense_1/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_category_attention_idx1/dense_2/kernel
  rown: 16
  scale_by_rown: true
- coln: 16
  dtype: float32
  init_mean: 0
  init_range: 1
  name: intent_aware_cross_category_attention_idx1/dense_3/kernel
  rown: 16
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: intent_aware_cross_category_attention_idx1/dense_3/bias
  rank: 1
  rown: 16
  scale_by_rown: true
- coln: 6
  dtype: float32
  init_mean: 0
  init_range: 1
  name: projection_idx0/dense/kernel
  rown: 48
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: projection_idx0/dense/bias
  rank: 1
  rown: 6
  scale_by_rown: true
- coln: 6
  dtype: float32
  init_mean: 0
  init_range: 1
  name: projection_idx1/dense/kernel
  rown: 48
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: projection_idx1/dense/bias
  rank: 1
  rown: 6
  scale_by_rown: true
q_names: like_weight follow_weight forward_weight comment_weight longview_weight effective_view_weight
  like_weight_idx1 follow_weight_idx1 forward_weight_idx1 comment_weight_idx1 longview_weight_idx1
  effective_view_weight_idx1
summary:
- len: 1912
  name: base_summary
- len: 2072
  name: stub_summary
summary_decay_rate: 0.999999
summary_init_n: 1e4
summary_init_squared_sum: 1e4
summary_squared_sum_epsilon: 1e-4
test_layers_at_joining: join join_forward update update_forward
test_layers_at_updating: update update_forward
test_mode: false
train_layers_at_joining: join
train_layers_at_updating: update
vec_input:
- common: false
  dim: 1
  name: pltr_idx0
- common: false
  dim: 1
  name: pwtr_idx0
- common: false
  dim: 1
  name: pftr_idx0
- common: false
  dim: 1
  name: pcmtr_idx0
- common: false
  dim: 1
  name: plvtr_idx0
- common: false
  dim: 1
  name: pctr_idx0
- common: false
  dim: 1
  name: pltr_idx1
- common: false
  dim: 1
  name: pwtr_idx1
- common: false
  dim: 1
  name: pftr_idx1
- common: false
  dim: 1
  name: pcmtr_idx1
- common: false
  dim: 1
  name: plvtr_idx1
- common: false
  dim: 1
  name: pctr_idx1
- common: false
  dim: 1
  name: level_reward_idx0
- common: false
  dim: 1
  name: level_reward_idx1
- common: false
  dim: 1
  name: like_idx0
- common: false
  dim: 1
  name: like_idx1
- common: false
  dim: 1
  name: follow_idx0
- common: false
  dim: 1
  name: follow_idx1
- common: false
  dim: 1
  name: forward_idx0
- common: false
  dim: 1
  name: forward_idx1
- common: false
  dim: 1
  name: comment_idx0
- common: false
  dim: 1
  name: comment_idx1
- common: false
  dim: 1
  name: click_comment_button_idx0
- common: false
  dim: 1
  name: click_comment_button_idx1
- common: false
  dim: 1
  name: long_view_idx0
- common: false
  dim: 1
  name: long_view_idx1
- common: false
  dim: 1
  name: effective_view_idx0
- common: false
  dim: 1
  name: effective_view_idx1
