ada_decay_rate: 0.99999
ada_epsilon: 1e-8
avg_decay_rate: 0.999993
back_propagate_input: true
embedding:
  create_threshold: 0
  initial_g2sum: 3
  initial_range: 2
  learning_rate: 0.05
  slots_config:
  - compress_group: USER
    dim: 4
    dtype: float32
    input_name: user_embedding
    slots: 101 102
  - compress_group: USER
    dim: 64
    dtype: float32
    input_name: pid_embedding
    slots: '103'
  - compress_group: USER
    dim: 64
    dtype: float32
    input_name: aid_embedding
    slots: '104'
  - compress_group: USER
    dim: 64
    dtype: float32
    input_name: uid_embedding
    slots: '105'
  - compress_group: USER
    dim: 64
    dtype: float32
    input_name: did_embedding
    slots: '106'
  - compress_group: USER
    dim: 32
    dtype: float32
    input_name: context_embedding
    slots: 110 111
  - dim: 64
    dtype: float32
    input_name: c_id_embedding
    slots: 201 202
  - dim: 32
    dtype: float32
    input_name: c_info_embedding
    slots: 203 204 205 206 207 209
  - dim: 8
    dtype: float32
    input_name: position_embedding
    slots: '208'
  - dim: 8
    dtype: float32
    input_name: comment_genre_embedding
    slots: '250'
  - dim: 32
    dtype: float32
    input_name: comment_length_embedding
    slots: '251'
  version_aware: true
  weight_bounds:
  - -10
  - 10
extra_params: []
extra_preds: expand_xtr like_xtr reply_xtr copy_xtr share_xtr audience_xtr continuous_expand_xtr
  duration_predict
global_init_range: 0.2
graph: ../config/graph.pb
graph_targets:
- opt
graph_tensor_mapping:
  audience_xtr: main_model/audience_xtr/dense_1/Sigmoid:0
  continuous_expand_xtr: main_model/continuous_expand_xtr/dense_1/Sigmoid:0
  copy_xtr: main_model/copy_xtr/dense_1/Sigmoid:0
  duration_predict: main_model/duration_predict/dense_1/Relu:0
  expand_xtr: main_model/expand_xtr/dense_1/Sigmoid:0
  like_xtr: main_model/like_xtr/dense_1/Sigmoid:0
  reply_xtr: main_model/reply_xtr/dense_1/Sigmoid:0
  share_xtr: main_model/share_xtr/dense_1/Sigmoid:0
hyperparameter_kconf: null
input_type: 3
is_train_placeholder: is_train:0
learning_rate: 5.0e-06
mom_decay_rate: 0.999
output_hidden_units: update_input continue_normlized_input slide_embedding slide_wide
  watch_time_wide position_weight_input
param:
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_expand_xtr/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_expand_xtr/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_expand_xtr/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_expand_xtr/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_like_xtr/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_like_xtr/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_like_xtr/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_like_xtr/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_reply_xtr/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_reply_xtr/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_reply_xtr/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_reply_xtr/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_copy_xtr/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_copy_xtr/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_copy_xtr/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_copy_xtr/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_share_xtr/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_share_xtr/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_share_xtr/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_share_xtr/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_audience_xtr/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_audience_xtr/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_audience_xtr/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_audience_xtr/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_continuous_expand_xtr/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_continuous_expand_xtr/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_continuous_expand_xtr/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_continuous_expand_xtr/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_duration_predict/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_duration_predict/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_duration_predict/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_duration_predict/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_shared_0/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_shared_0/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_shared_0/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_shared_0/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_shared_1/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_shared_1/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_shared_1/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_shared_1/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_shared_2/dense/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_shared_2/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expert_shared_2/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expert_shared_2/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 4
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/gate_model/gate_0/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/gate_model/gate_0/bias
  rank: 1
  rown: 4
  scale_by_rown: true
- coln: 4
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/gate_model/gate_1/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/gate_model/gate_1/bias
  rank: 1
  rown: 4
  scale_by_rown: true
- coln: 4
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/gate_model/gate_2/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/gate_model/gate_2/bias
  rank: 1
  rown: 4
  scale_by_rown: true
- coln: 4
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/gate_model/gate_3/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/gate_model/gate_3/bias
  rank: 1
  rown: 4
  scale_by_rown: true
- coln: 4
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/gate_model/gate_4/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/gate_model/gate_4/bias
  rank: 1
  rown: 4
  scale_by_rown: true
- coln: 4
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/gate_model/gate_5/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/gate_model/gate_5/bias
  rank: 1
  rown: 4
  scale_by_rown: true
- coln: 4
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/gate_model/gate_6/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/gate_model/gate_6/bias
  rank: 1
  rown: 4
  scale_by_rown: true
- coln: 4
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/gate_model/gate_7/kernel
  rown: 688
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/gate_model/gate_7/bias
  rank: 1
  rown: 4
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expand_xtr/dense/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expand_xtr/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expand_xtr/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expand_xtr/dense_1/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/like_xtr/dense/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/like_xtr/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/like_xtr/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/like_xtr/dense_1/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/reply_xtr/dense/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/reply_xtr/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/reply_xtr/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/reply_xtr/dense_1/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/copy_xtr/dense/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/copy_xtr/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/copy_xtr/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/copy_xtr/dense_1/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/share_xtr/dense/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/share_xtr/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/share_xtr/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/share_xtr/dense_1/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/audience_xtr/dense/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/audience_xtr/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/audience_xtr/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/audience_xtr/dense_1/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/continuous_expand_xtr/dense/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/continuous_expand_xtr/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/continuous_expand_xtr/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/continuous_expand_xtr/dense_1/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/duration_predict/dense/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/duration_predict/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/duration_predict/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/duration_predict/dense_1/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/bias_duration_predict/dense/kernel
  rown: 136
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/bias_duration_predict/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/bias_duration_predict/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/bias_duration_predict/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/bias_duration_predict/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/bias_duration_predict/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
q_names: expand_xtr like_xtr reply_xtr copy_xtr share_xtr audience_xtr continuous_expand_xtr
  duration_predict
summary:
- len: 1912
  name: base_summary
- len: 2072
  name: stub_summary
summary_decay_rate: 0.999999
summary_init_n: 1e4
summary_init_squared_sum: 1e4
summary_squared_sum_epsilon: 1e-4
test_layers_at_joining: join join_forward update update_forward
test_layers_at_updating: update update_forward
test_mode: false
train_layers_at_joining: join
train_layers_at_updating: update
