ada_decay_rate: 0.99999
ada_epsilon: 1e-8
avg_decay_rate: 0.999993
back_propagate_input: true
embedding:
  create_threshold: 0
  initial_g2sum: 3
  initial_range: 2
  learning_rate: 0.05
  slots_config:
  - compress_group: USER
    dim: 4
    dtype: float32
    input_name: user_profile_emb
    slots: 101 102
  - compress_group: USER
    dim: 64
    dtype: float32
    input_name: personalized_id_emb
    slots: 103 104 105 106
  - compress_group: USER
    dim: 64
    dtype: float32
    input_name: context_emb
    slots: 110 111 113
  - compress_group: USER
    dim: 4
    dtype: float32
    input_name: video_profile_emb
    slots: '112'
  - dim: 64
    dtype: float32
    input_name: c_id_emb
    slots: 201 202
  - dim: 32
    dtype: float32
    input_name: c_info_emb
    slots: 203 204 205 206 207 209
  - dim: 8
    dtype: float32
    input_name: c_position_emb
    slots: '208'
  - dim: 8
    dtype: float32
    input_name: c_tag_emb
    slots: 250 254 255
  - dim: 12
    dtype: float32
    input_name: c_cnt_emb
    slots: 271 272 273 274 275 276 277 286 287 288 289 290 291
  - dim: 8
    dtype: float32
    input_name: c_mmu_score_emb
    slots: '279'
  - dim: 8
    dtype: float32
    input_name: c_xtr_emb
    slots: 281 282 283 284 285
  - dim: 4
    dtype: float32
    input_name: c_binary_tag_emb
    slots: 270 292 293 294 295 296 297 298
  version_aware: true
  weight_bounds:
  - -10
  - 10
extra_params: []
extra_preds: expand_xtr like_xtr reply_xtr copy_xtr share_xtr audience_xtr continuous_expand_xtr
global_init_range: 0.2
graph: ../config/graph.pb
graph_targets:
- opt
graph_tensor_mapping:
  audience_xtr: main_model/audience/dense_2/Sigmoid:0
  continuous_expand_xtr: main_model/continuous_expand/dense_2/Sigmoid:0
  copy_xtr: main_model/copy/dense_2/Sigmoid:0
  expand_xtr: main_model/expand/dense_2/Sigmoid:0
  like_xtr: main_model/like/dense_2/Sigmoid:0
  reply_xtr: main_model/reply/dense_2/Sigmoid:0
  share_xtr: main_model/share/dense_2/Sigmoid:0
hyperparameter_kconf: null
input_type: 3
is_train_placeholder: is_train:0
learning_rate: 5.0e-06
mom_decay_rate: 0.999
output_hidden_units: update_input continue_normlized_input slide_embedding slide_wide
  watch_time_wide position_weight_input
param:
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/explicit_cross_layer_0/dense/kernel
  rown: 1048
  scale_by_rown: true
- coln: 1048
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/explicit_cross_layer_0/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/explicit_cross_layer_0/dense_1/bias
  rank: 1
  rown: 1048
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/explicit_cross_layer_1/dense/kernel
  rown: 1048
  scale_by_rown: true
- coln: 1048
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/explicit_cross_layer_1/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/explicit_cross_layer_1/dense_1/bias
  rank: 1
  rown: 1048
  scale_by_rown: true
- coln: 512
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/dense/kernel
  rown: 1048
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/dense/bias
  rank: 1
  rown: 512
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expand/dense/kernel
  rown: 512
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expand/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expand/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expand/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/expand/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/expand/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/like/dense/kernel
  rown: 512
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/like/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/like/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/like/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/like/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/like/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/reply/dense/kernel
  rown: 512
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/reply/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/reply/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/reply/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/reply/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/reply/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/copy/dense/kernel
  rown: 512
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/copy/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/copy/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/copy/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/copy/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/copy/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/share/dense/kernel
  rown: 512
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/share/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/share/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/share/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/share/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/share/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/audience/dense/kernel
  rown: 512
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/audience/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/audience/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/audience/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/audience/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/audience/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/continuous_expand/dense/kernel
  rown: 512
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/continuous_expand/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/continuous_expand/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/continuous_expand/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: main_model/continuous_expand/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: main_model/continuous_expand/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
q_names: expand_xtr like_xtr reply_xtr copy_xtr share_xtr audience_xtr continuous_expand_xtr
summary:
- len: 1912
  name: base_summary
- len: 2072
  name: stub_summary
summary_decay_rate: 0.999999
summary_init_n: 1e4
summary_init_squared_sum: 1e4
summary_squared_sum_epsilon: 1e-4
test_layers_at_joining: join join_forward update update_forward
test_layers_at_updating: update update_forward
test_mode: false
train_layers_at_joining: join
train_layers_at_updating: update
