ada_decay_rate: 0.99999
ada_epsilon: 1e-8
avg_decay_rate: 0.999993
back_propagate_input: true
embedding:
  create_threshold: 0
  initial_g2sum: 3
  initial_range: 2
  learning_rate: 0.05
  slots_config:
  - compress_group: USER
    dim: 64
    dtype: float32
    input_name: user_emb
    slots: 300 301
  - compress_group: USER
    dim: 4
    dtype: float32
    input_name: uid_stat
    slots: '302'
  - compress_group: USER
    dim: 64
    dtype: float32
    expand: 3
    input_name: bi_friend_uid_emb
    slots: '229'
  - dim: 64
    dtype: float32
    input_name: pid_emb
    slots: 200 201
  - dim: 8
    dtype: float32
    input_name: pid_stat
    slots: 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219
      220 221 222 223 224 225 226 227 228
  version_aware: true
  weight_bounds:
  - -10
  - 10
extra_params: []
extra_preds: open_xtr at_xtr at_open_xtr comment_at_open_xtr
global_init_range: 0.2
graph: ../config/graph.pb
graph_targets:
- opt
graph_tensor_mapping:
  at_open_xtr: comment_layer/at_open_xtr/dense_2/Sigmoid:0
  at_xtr: comment_layer/at_xtr/dense_2/Sigmoid:0
  comment_at_open_xtr: comment_layer/mul:0
  open_xtr: forward_layer/forward_inside_open_xtr/dense_2/Sigmoid:0
hyperparameter_kconf: null
input_type: 3
is_train_placeholder: is_train:0
learning_rate: 5.0e-06
mom_decay_rate: 0.999
output_hidden_units: update_input continue_normlized_input slide_embedding slide_wide
  watch_time_wide position_weight_input
param:
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: forward_layer/forward_xtr/dense/kernel
  rown: 540
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: forward_layer/forward_xtr/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: forward_layer/forward_xtr/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: forward_layer/forward_xtr/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: forward_layer/forward_xtr/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: forward_layer/forward_xtr/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: forward_layer/forward_inside_xtr/dense/kernel
  rown: 540
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: forward_layer/forward_inside_xtr/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: forward_layer/forward_inside_xtr/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: forward_layer/forward_inside_xtr/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: forward_layer/forward_inside_xtr/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: forward_layer/forward_inside_xtr/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: forward_layer/forward_inside_open_xtr/dense/kernel
  rown: 540
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: forward_layer/forward_inside_open_xtr/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: forward_layer/forward_inside_open_xtr/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: forward_layer/forward_inside_open_xtr/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: forward_layer/forward_inside_open_xtr/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: forward_layer/forward_inside_open_xtr/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: comment_layer/at_xtr/dense/kernel
  rown: 540
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: comment_layer/at_xtr/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: comment_layer/at_xtr/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: comment_layer/at_xtr/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: comment_layer/at_xtr/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: comment_layer/at_xtr/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: comment_layer/at_open_xtr/dense/kernel
  rown: 540
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: comment_layer/at_open_xtr/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: comment_layer/at_open_xtr/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: comment_layer/at_open_xtr/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: comment_layer/at_open_xtr/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: comment_layer/at_open_xtr/dense_2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
q_names: open_xtr at_xtr at_open_xtr comment_at_open_xtr
summary:
- len: 1912
  name: base_summary
- len: 2072
  name: stub_summary
summary_decay_rate: 0.999999
summary_init_n: 1e4
summary_init_squared_sum: 1e4
summary_squared_sum_epsilon: 1e-4
test_layers_at_joining: join join_forward update update_forward
test_layers_at_updating: update update_forward
test_mode: false
train_layers_at_joining: join
train_layers_at_updating: update
